[package]
name = "advance_course"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "advance_course"
[dependencies]
common = { path = "../common" }