[package]
name = "basic_course"
version = "0.1.0"
edition = "2021"

[lib]
name="basic_course"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
inline-c = "0.1"